#!/bin/bash -e
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

dotnet run -p ${HOME}/project.json --server.urls=http://*:5000
